version: "3"
services:
  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
      - "8085:8085"
volumes:
  - ./host-nexus-data:/nexus-data
 # nexus-data: {}



 #make the volume dir in docker host
    #mkdir ./host-nexus-data
    #chown 200:200 ./host-nexus-data
