- name: import the elasticsearch apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  become: true

- name: install elasticsearch 6.x deb repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present
  become: true

- name: install elasticsearch 6.x
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - openjdk-8-jre-headless
    - elasticsearch
  become: true
