- name: Nexus Repo-Playbook Conditional
  hosts: all
  become: yes

  tasks:
    - name: Copy nexus repo for debian
      copy:
        src: ./repository/sources.list
        dest: /etc/apt/sourcrs.list
        owner: root
        group: root
        mode: '0644'
        backup: yes
      when:
        - ansible_os_family == "Debian"


    - name: Copy nexus repo for Centos
      src: ./repository/centos.repo
        dest: /etc/yum.repos.d/centos.repo
        owner: root
        group: root
        mode: '0644'
        backup: yes
      when: 
        - ansible_os_family == "RedHat"

  # mkdir -p ./repository
