 ## Add this- name: kubernetes installation
  hosts: masters,workers
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  #kubernetes add repo, kubectl,kubeadm,kubelet install and kubelet start
    - name: Copy kubernetes repo
      copy: 
        src: kubernetes.repo 
        dest: /etc/yum.repos.d/kubernetes.repo
    - name: Install kubelet kubeadm kubectl
      shell: |
        sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
    - name: Start and enable
      service: 
        name: kubelet
        state: started 
        enabled: yes
    - name: reboot
      reboot:
        reboot_timeout: 2600
