apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    component: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      component: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        component: wordpress
    spec:
      containers:
      - image: wordpress:4.9-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb 
        - name: WORDPRESS_DB_PASSWORD
          value: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
      volumes:
      - name: wordpress-data
        hostPath:
          path: /data/wordpress
          type: DirectoryOrCreate
