

### add ungrouped
ungrouped:
  hosts:
    ubuntu-lvm:
### add group    
ubuntu-servers:
  hosts:
    Docker-1: 
    Docker-2: 
    Gitlab: 
    kub-worker1: 
    kub-worker2: 
    kubrneties: 
    prometheus:    
centos-servers:
  hosts:
    centos9:

### add subgroup
all:
  children:
    ubuntu-servers:
    centos-servers:
    
