

### add ungrouped####################################################
ungrouped:
  hosts:
    ubuntu-lvm:  
      ansible_host: 10.10.11.111
      ansible_user: root
      ansible_password: 123456@
      ansible_port: 5555
      
### add group ########################################################   
ubuntu-servers:
  hosts:
    docker-1: 
      ansible_host: 10.10.11.122
      ansible_password: 123456@
    docker-2: 
      ansible_host: 10.10.11.123
    gitlab:
      ansible_host: 10.10.11.124
    kub-worker1:
      ansible_host: 10.10.11.125
    kub-worker2:
      ansible_host: 10.10.11.126
    kubrneties: 
      ansible_host: 10.10.11.127
    prometheus:  
      ansible_host: 10.10.11.128
###### vars assign to group
  vars:
    ansible_user: root
    ntp_server: ntp.atlanta.example.com

  hosts:
    centos9:
      ansible_host: 10.10.11.110
     vars:
       ntp_server: ntp.atlanta.example.com
       proxy: proxy.atlanta.example.com

### add subgroup ########################################################
all:
  children:
    ubuntu-servers:
    centos-servers:
    
