#https://medium.com/@venkataramarao.n/kubernetes-setup-using-ansible-script-8dd6607745f6
#https://medium.com/@martin.hodges/installing-kubernetes-from-the-new-k8s-io-repository-using-ansible-8e7319fa97fd

k8s_url_apt_key: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"
k8s_gpgpath: /usr/share/keyrings/kubernetes-apt-keyring.gpg
k8s_repository: "https://pkgs.k8s.io/core:/stable:/v1.28/deb/"

---
- hosts: master
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        
- name: Get Kubernetes package key
     shell: curl -fsSL {{ k8s_url_apt_key }} | gpg --dearmor -o {{ k8s_gpgpath }}
     args:
       creates: "{{ k8s_gpgpath }}"

- name: Install Kubernetes repository
    apt_repository:
      filename: kubernetes
      repo: "deb [signed-by={{ k8s_gpgpath }}] {{ k8s_repository }} /"
        
- name: Install kubeadm, kubelet, and kubectl
    apt:
      name: "{{ item }}"
      state: present
      loop:
        - kubeadm
        - kubelet
        - kubectl

- name: Initialize Kubernetes master
    command: kubeadm init --pod-network-cidr=10.10.12.0/24
    register: kubeadm_output
    ignore_errors: yes

- name: Set up kubectl for the current user
    command: "{{ item }}"
    with_items:
      - "mkdir -p $HOME/.kube"
      - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
      - "chown $(id -u):$(id -g) $HOME/.kube/config"

- name: Install Calico network plugin
    command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    when: "'calico' in kubeadm_output.stdout"

- hosts: workers
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

- name: Install kubeadm, kubelet, and kubectl
    apt:
      name: "{{ item }}"
      state: present
      loop:
        - kubeadm
        - kubelet
        - kubectl

- name: Join worker nodes to the cluster
    command: "{{ hostvars['master']['kubeadm_output']['stdout_lines'][0] }}"
    when: "'kubeadm join' in hostvars['master']['kubeadm_output']['stdout']"
